# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: token-updater
# app and org for use with dashboard.serverless.com
app: token-updater
org: kadefimoney

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

functions:
  updatePrice:
    handler: handler.updatePriceHandler
    events:
      - schedule:
          rate: rate(1 minute)
    environment:
      PGHOST: ${param:PGHOST}
      PGUSER: ${param:PGUSER}
      PGDATABASE: ${param:PGDATABASE}
      PGPASSWORD: ${param:PGPASSWORD}
      PGPORT: 5432
    timeout: 30
  updateToken:
    handler: handler.updateTokenHandler
    events:
      - schedule:
          rate: rate(1 minute)
    environment:
      PGHOST: ${param:PGHOST}
      PGUSER: ${param:PGUSER}
      PGDATABASE: ${param:PGDATABASE}
      PGPASSWORD: ${param:PGPASSWORD}
      PGPORT: 5432
  candleUpdateKaddex:
    handler: handler.candleUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)
          input:
            dex: kaddex
    environment:
      PGHOST: ${param:PGHOST}
      PGUSER: ${param:PGUSER}
      PGDATABASE: ${param:PGDATABASE}
      PGPASSWORD: ${param:PGPASSWORD}
      PGPORT: 5432
  candleUpdateKDSwap:
    handler: handler.candleUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)
          input:
            dex: kdswap
    environment:
      PGHOST: ${param:PGHOST}
      PGUSER: ${param:PGUSER}
      PGDATABASE: ${param:PGDATABASE}
      PGPASSWORD: ${param:PGPASSWORD}
      PGPORT: 5432
  candleUpdateKaddex1:
    handler: handler.candleUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)
          input:
            dex: kaddex
    environment:
      PGHOST: ${param:PGHOST}
      PGUSER: ${param:PGUSER}
      PGDATABASE: ${param:PGDATABASE}
      PGPASSWORD: ${param:PGPASSWORD}
      PGPORT: 5432
  candleUpdateKDSwap1:
    handler: handler.candleUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)
          input:
            dex: kdswap
    environment:
      PGHOST: ${param:PGHOST}
      PGUSER: ${param:PGUSER}
      PGDATABASE: ${param:PGDATABASE}
      PGPASSWORD: ${param:PGPASSWORD}
      PGPORT: 5432
  candleUpdateAll:
    handler: handler.candleUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)
          input:
            dex: kdswap
      - schedule:
          rate: rate(1 minute)
          input:
            dex: kaddex
    environment:
      PGHOST: ${param:PGHOST}
      PGUSER: ${param:PGUSER}
      PGDATABASE: ${param:PGDATABASE}
      PGPASSWORD: ${param:PGPASSWORD}
      PGPORT: 5432
  materialViewUpdate:
    handler: handler.materialViewUpdateHandler
    events:
      - schedule:
          rate: rate(1 minute)
    environment:
      PGHOST: ${param:PGHOST}
      PGUSER: ${param:PGUSER}
      PGDATABASE: ${param:PGDATABASE}
      PGPASSWORD: ${param:PGPASSWORD}
      PGPORT: 5432
    timeout: 30