name: For Production

on:
push:
    branches: [master]
jobs:
build:
    runs-on: ubuntu-latest

    strategy:
    matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
    - run: npm ci
    - name: Install Serverless Framework
        run: npm install -g serverless
    - name: Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    - name: Deploy to AWS
        run: serverless deploy --verbose --param PGHOST=${{secrets.PGHOST}} --param PGUSER=${{secrets.PGUSER}} --param PGDATABASE=${{secrets.PGDATABASE}} --param PGPASSWORD=${{secrets.PGPASSWORD}}
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}